# Generated by Django 3.2.4 on 2021-08-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210816_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='/media/pro_pics/default.png', upload_to='pro_pics'),
        ),
    ]
