# Generated by Django 3.2.4 on 2021-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='pro_pics/default.png', upload_to='pro_pics'),
        ),
    ]
